FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./
COPY node_modules ./node_modules
COPY build ./build

RUN apk fix && \
    apk --no-cache --update add git git-lfs less openssh && \
    git lfs install

EXPOSE 3000

CMD ["node", "./build/index.js"]
