name: Docker Build CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "**/*.md"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: iszy-webhook

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read package.json
        id: package-version
        run: echo "version=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.ref_name == 'main' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}},value=${{ steps.package-version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.package-version.outputs.version }}

      - name: Extract metadata (tags, labels) for Docker (DEV)
        if: ${{ github.ref_name != 'main' }}
        id: meta-dev
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (DEV)
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}

  build-git:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build app
        run: pnpm run build

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Read package.json
        id: package-version
        run: echo "version=$(node -p -e "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.ref_name == 'main' }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-git
          tags: |
            type=semver,pattern={{version}},value=${{ steps.package-version.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ steps.package-version.outputs.version }}

      - name: Extract metadata (tags, labels) for Docker (DEV)
        if: ${{ github.ref_name != 'main' }}
        id: meta-dev
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}-git
          tags: |
            type=ref,event=branch

      - name: Build and push Docker image
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push Docker image (DEV)
        if: ${{ github.ref_name != 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile-git
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-dev.outputs.tags }}
          labels: ${{ steps.meta-dev.outputs.labels }}
